# Problem 1

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrixA = np.linspace(0, 10, 5)
matrixB = matrixA.reshape(1, 5)

# 3 - matris'in boyutunu öğrenin
print("Matris boyutu:", matrixB.shape)

# 4 - matris'i yeniden boyutlandırın
yeni_matrix = matrixB.reshape(5,1 )

# 5 - matris'in boyut sayısını öğrenin
print("Orijinal Matris:\n", matrixB)
print("Yeniden Boyutlandırılmış Matris:\n", yeni_matrix)


Matris boyutu: (1, 5)
Orijinal Matris:
 [[ 0.   2.5  5.   7.5 10. ]]
Yeniden Boyutlandırılmış Matris:
 [[ 0. ]
 [ 2.5]
 [ 5. ]
 [ 7.5]
 [10. ]]


# Problem 2

In [18]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1, 10, 2)

# 2 - Oluşturduğunuz matrisi parçalayın
matrix = matris.reshape(5, 1)
matris_böl = np.split(matrix, 5)
print(matris_böl)

# 3 - Parçalanmış matrisleri birleştirin
matris_birlestir = np.concatenate(matris_böl, axis=0)
print(matris_birlestir)

[array([[1]]), array([[3]]), array([[5]]), array([[7]]), array([[9]])]
[[1]
 [3]
 [5]
 [7]
 [9]]


# Problem 3

In [19]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayılar = np.arange(5, 101, 2)
matris = np.random.choice(sayılar, size=10, replace=False)
matrix = matris.reshape(2, 5)

# 2 - matris'in özelliklerini inceleyin
print("Matris:\n", matrix)
print("Matris Boyut Sayısı-ndim:", matrix.ndim)
print("Matris Şekli-shape:", matrix.shape)
print("Matris Eleman Sayısı-size:", matrix.size)
print("Matris Veri Tipi-dtype:", matrix.dtype)
print("Matris Ortalama-mean:", matrix.mean())
print("Matris Toplam-sum:", matrix.sum())


Matris:
 [[65 41 89 39 79]
 [59 43 19 71 31]]
Matris Boyut Sayısı-ndim: 2
Matris Şekli-shape: (2, 5)
Matris Eleman Sayısı-size: 10
Matris Veri Tipi-dtype: int32
Matris Ortalaması-mean: 53.6
Matris Toplamı-sum: 536
