# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([7, 2, 23, 1, 9])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sıralı_array = np.sort(array)
print(sıralı_array)


[ 1  2  7  9 23]


# Problem 2

In [12]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
arrayA = np.array([10, 15, 30, 45, 60])
print("A :", arrayA)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arrayB = np.arange(5, 16)
print("B :", arrayB)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arrayC = np.arange(50, 101, 5)
print("C :", arrayC)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
arrayD = np.zeros(10)
print("D :", arrayD)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
arrayE = np.ones(10)
print("E :", arrayE)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arrayF = np.linspace(0, 100, 5)
print("F :", arrayF)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
arrayG = np.random.randint(10, 31, size=5)
print("G :", arrayG)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
arrayH = np.random.uniform(-1, 1, 10)
print("H :\n", arrayH)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrixI = np.random.randint(10, 51, size=(3, 5))
print("I :\n", matrixI)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print("10-")
satir, sütun = matrixI.shape
sum = satir + sütun
print("Satır ve sütun sayıları toplamı:", sum)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("11-")
max_value = np.max(matrixI)
min_value = np.min(matrixI)
mean_value = np.mean(matrixI)
print("En büyük değer:", max_value)
print("En küçük değer:", min_value)
print("Ortalama değer:", mean_value)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print("12-")
max_indeks = np.argmax(matrixI)
print("En büyük değerinin indeksi:", max_indeks)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
print("13-")
arrayJ = np.arange(10, 21)
uc_eleman = arrayJ[:3]
print("İlk 3 eleman:", uc_eleman)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("14-")
ters_arrayJ = arrayJ[::-1]
print("Tersten dizinin elemanları:", ters_arrayJ)

# 15- Üretilen matrisin ilk satırını seçiniz.
print("15-")
ilk_satir = matrixI[0]
print("İlk satır:", ilk_satir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("16-")
eleman_2_3 = matrixI[1,2]
print("2. satır 3. sütun elemanı:", eleman_2_3)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("17-")
ilk_eleman = matrixI[:, 0]
print("Her satırın ilk elemanı:", ilk_eleman)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("18-")
kare_matrix = np.square(matrixI)
print("Elemanların karesi:\n", kare_matrix)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
print("19-")
matrix_son = np.random.randint(-50, 51, size=(3, 5))
cift_ve_pozitif = matrix_son[(matrix_son % 2 == 0) & (matrix_son > 0)]
print("Pozitif çift sayılar:\n", cift_ve_pozitif)


A : [10 15 30 45 60]
B : [ 5  6  7  8  9 10 11 12 13 14 15]
C : [ 50  55  60  65  70  75  80  85  90  95 100]
D : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
E : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
F : [  0.  25.  50.  75. 100.]
G : [18 14 20 20 20]
H :
 [-0.71614168  0.58089589  0.15091102 -0.37463085 -0.32777254 -0.45044637
  0.8679944  -0.1285807  -0.99129565 -0.02104746]
I :
 [[34 41 28 21 50]
 [39 43 45 11 28]
 [40 40 16 28 38]]
10-
Satır ve sütun sayıları toplamı: 8
11-
En büyük değer: 50
En küçük değer: 11
Ortalama değer: 33.46666666666667
12-
En büyük değerinin indeksi: 4
13-
İlk 3 eleman: [10 11 12]
14-
Tersten dizinin elemanları: [20 19 18 17 16 15 14 13 12 11 10]
15-
İlk satır: [34 41 28 21 50]
16-
2. satır 3. sütun elemanı: 45
17-
Her satırın ilk elemanı: [34 39 40]
18-
Elemanların karesi:
 [[1156 1681  784  441 2500]
 [1521 1849 2025  121  784]
 [1600 1600  256  784 1444]]
19-
Pozitif çift sayılar:
 [44 20 36 26 28]
